/**
 * @file config_app.h
 * @brief Configuration file for Wall Controller sample application.
 * @copyright Copyright (c) 2001-2017
 * Sigma Designs, Inc.
 * All Rights Reserved
 * @details This file contains definitions for the Z-Wave+ Framework as well for the sample app.
 *
 * NOTICE: The file name must not be changed and the two definitions APP_VERSION and APP_REVISION
 * must not be changed since they are used by the build environment.
 */
#ifndef _CONFIG_APP_H_
#define _CONFIG_APP_H_

#ifdef __C51__
#include <ZW_product_id_enum.h>
#include <commandClassManufacturerSpecific.h>
#include <agi.h>
#endif
#include <app_config_common.h>

/**
 * Defines device generic and specific types
 */
//@ [GENERIC_TYPE_ID]
#define GENERIC_TYPE          GENERIC_TYPE_WALL_CONTROLLER
#define SPECIFIC_TYPE         SPECIFIC_TYPE_BASIC_WALL_CONTROLLER
//@ [GENERIC_TYPE_ID]

/**
 * See ZW_basic_api.h for ApplicationNodeInformation field deviceOptionMask
 */
//@ [DEVICE_OPTIONS_MASK_ID]
#define DEVICE_OPTIONS_MASK   APPLICATION_NODEINFO_LISTENING | APPLICATION_NODEINFO_OPTIONAL_FUNCTIONALITY
//@ [DEVICE_OPTIONS_MASK_ID]


/**
 * Defines used to initialize the Z-Wave Plus Info Command Class.
 */
//@ [APP_TYPE_ID]
//@ [APP_ROLE_TYPE]
#define APP_ROLE_TYPE       ZWAVEPLUS_INFO_REPORT_ROLE_TYPE_SLAVE_ALWAYS_ON
#define APP_NODE_TYPE       ZWAVEPLUS_INFO_REPORT_NODE_TYPE_ZWAVEPLUS_NODE
#define APP_ICON_TYPE       ICON_TYPE_GENERIC_WALL_CONTROLLER
#define APP_USER_ICON_TYPE  ICON_TYPE_GENERIC_WALL_CONTROLLER
//@ [APP_ROLE_TYPE]
//@ [ENDPOINT_ICONS]
#define ENDPOINT_ICONS \
 {ICON_TYPE_GENERIC_LIGHT_DIMMER_SWITCH, ICON_TYPE_GENERIC_LIGHT_DIMMER_SWITCH},\
 {ICON_TYPE_GENERIC_LIGHT_DIMMER_SWITCH, ICON_TYPE_GENERIC_LIGHT_DIMMER_SWITCH},\
 {ICON_TYPE_GENERIC_LIGHT_DIMMER_SWITCH, ICON_TYPE_GENERIC_LIGHT_DIMMER_SWITCH},\
 {ICON_TYPE_GENERIC_LIGHT_DIMMER_SWITCH, ICON_TYPE_GENERIC_LIGHT_DIMMER_SWITCH}
 //@ [ENDPOINT_ICONS]
//@ [APP_TYPE_ID]

/**
 * Defines used to initialize the Manufacturer Specific Command Class.
 */
 //@ [APP_MANUFACTURER_ID]
#define APP_MANUFACTURER_ID     MFG_ID_SIGMA_DESIGNS

#define APP_PRODUCT_TYPE_ID     PRODUCT_TYPE_ID_ZWAVE_PLUS
#define APP_PRODUCT_ID          PRODUCT_ID_WallController

#define APP_DEVICE_ID_TYPE      DEVICE_ID_TYPE_SERIAL_NBR
#define APP_DEVICE_ID_FORMAT    DEVICE_ID_FORMAT_BIN
//@ [APP_MANUFACTURER_ID]

//@ [APP_FIRMWARE_ID]
#define APP_FIRMWARE_ID         APP_PRODUCT_ID | (APP_PRODUCT_TYPE_ID << 8)
//@ [APP_FIRMWARE_ID]

/**
 * Defines used to initialize the Association Group Information (AGI)
 * Command Class.
 */
#define NUMBER_OF_INDIVIDUAL_ENDPOINTS    4
#define NUMBER_OF_AGGREGATED_ENDPOINTS    0
#define NUMBER_OF_ENDPOINTS         NUMBER_OF_INDIVIDUAL_ENDPOINTS + NUMBER_OF_AGGREGATED_ENDPOINTS
#define MAX_ASSOCIATION_GROUPS      3
#define MAX_ASSOCIATION_IN_GROUP    5

//@ [AGI_TABLE_ID]
//@ [AGITABLE_LIFELINE_GROUP]
#define AGITABLE_LIFELINE_GROUP \
 {COMMAND_CLASS_CENTRAL_SCENE_V2, CENTRAL_SCENE_NOTIFICATION_V2}, \
 {COMMAND_CLASS_DEVICE_RESET_LOCALLY, DEVICE_RESET_LOCALLY_NOTIFICATION}
//@ [AGITABLE_LIFELINE_GROUP]

/*
 * LifeLine group for all endpoints.
 * One define since they're all the same.
 */
//@ [AGITABLE_LIFELINE_GROUP_EP1_2_3_4]
#define AGITABLE_LIFELINE_GROUP_EP1_2_3_4 \
	{COMMAND_CLASS_CENTRAL_SCENE_V2, CENTRAL_SCENE_NOTIFICATION_V2}
//@ [AGITABLE_LIFELINE_GROUP_EP1_2_3_4]

//@ [AGITABLE_ROOTDEVICE_GROUPS]
#define  AGITABLE_ROOTDEVICE_GROUPS \
 AGITABLE_ENDPOINT_1_GROUPS, \
 AGITABLE_ENDPOINT_2_GROUPS, \
 AGITABLE_ENDPOINT_3_GROUPS, \
 AGITABLE_ENDPOINT_4_GROUPS
//@ [AGITABLE_ROOTDEVICE_GROUPS]

/*
 * Endpoint groups.
 */
//@ [AGITABLE_ENDPOINT_1_GROUPS]
#define  AGITABLE_ENDPOINT_1_GROUPS \
 {ASSOCIATION_GROUP_INFO_REPORT_PROFILE_CONTROL, ASSOCIATION_GROUP_INFO_REPORT_PROFILE_CONTROL_KEY01, {COMMAND_CLASS_BASIC_V2, BASIC_SET_V2}, "Button S2"}, \
 {ASSOCIATION_GROUP_INFO_REPORT_PROFILE_CONTROL, ASSOCIATION_GROUP_INFO_REPORT_PROFILE_CONTROL_KEY01, {COMMAND_CLASS_SWITCH_MULTILEVEL_V4, SWITCH_MULTILEVEL_SET_V4}, "Button S2"}
//@ [AGITABLE_ENDPOINT_1_GROUPS]

#define  AGITABLE_ENDPOINT_2_GROUPS \
 {ASSOCIATION_GROUP_INFO_REPORT_PROFILE_CONTROL, ASSOCIATION_GROUP_INFO_REPORT_PROFILE_CONTROL_KEY02, {COMMAND_CLASS_BASIC_V2, BASIC_SET_V2}, "NOT USED"}, \
 {ASSOCIATION_GROUP_INFO_REPORT_PROFILE_CONTROL, ASSOCIATION_GROUP_INFO_REPORT_PROFILE_CONTROL_KEY02, {COMMAND_CLASS_SWITCH_MULTILEVEL_V4, SWITCH_MULTILEVEL_SET_V4}, "NOT USED"}

#define  AGITABLE_ENDPOINT_3_GROUPS \
 {ASSOCIATION_GROUP_INFO_REPORT_PROFILE_CONTROL, ASSOCIATION_GROUP_INFO_REPORT_PROFILE_CONTROL_KEY03, {COMMAND_CLASS_BASIC_V2, BASIC_SET_V2}, "Button S4"}, \
 {ASSOCIATION_GROUP_INFO_REPORT_PROFILE_CONTROL, ASSOCIATION_GROUP_INFO_REPORT_PROFILE_CONTROL_KEY03, {COMMAND_CLASS_SWITCH_MULTILEVEL_V4, SWITCH_MULTILEVEL_SET_V4}, "Button S4"}

#define  AGITABLE_ENDPOINT_4_GROUPS \
 {ASSOCIATION_GROUP_INFO_REPORT_PROFILE_CONTROL, ASSOCIATION_GROUP_INFO_REPORT_PROFILE_CONTROL_KEY04, {COMMAND_CLASS_BASIC_V2, BASIC_SET_V2}, "Button S6"}, \
 {ASSOCIATION_GROUP_INFO_REPORT_PROFILE_CONTROL, ASSOCIATION_GROUP_INFO_REPORT_PROFILE_CONTROL_KEY04, {COMMAND_CLASS_SWITCH_MULTILEVEL_V4, SWITCH_MULTILEVEL_SET_V4}, "Button S6"}
//@ [AGI_TABLE_ID]

/**
 *  mapping root group to endpoint group:
 *  Root group -> endpoint, endpoint-group
 */
//@ [ASSOCIATION_ROOT_GROUP_MAPPING_CONFIG]
#define ASSOCIATION_ROOT_GROUP_MAPPING_CONFIG \
  {ASS_GRP_ID_2, ENDPOINT_1, ASS_GRP_ID_2}, \
  {ASS_GRP_ID_3, ENDPOINT_1, ASS_GRP_ID_3}, \
  {ASS_GRP_ID_4, ENDPOINT_2, ASS_GRP_ID_2}, \
  {ASS_GRP_ID_5, ENDPOINT_2, ASS_GRP_ID_3}, \
  {ASS_GRP_ID_6, ENDPOINT_3, ASS_GRP_ID_2}, \
  {ASS_GRP_ID_7, ENDPOINT_3, ASS_GRP_ID_3}, \
  {ASS_GRP_ID_8, ENDPOINT_4, ASS_GRP_ID_2}, \
  {ASS_GRP_ID_9, ENDPOINT_4, ASS_GRP_ID_3}
//@ [ASSOCIATION_ROOT_GROUP_MAPPING_CONFIG]


//@ [FIRMWARE_UPGRADABLE]
#define FIRMWARE_UPGRADABLE    0xff /**< 0x00 = Not upgradable, 0xFF = Upgradable*/
//@ [FIRMWARE_UPGRADABLE]

/**
 * configuration for ApplicationUtilities/multilevel_switch.h + .c
 */
#define SWITCH_MULTI_ENDPOINTS  4

//@ [SECURITY_AUTHENTICATION_ID]
/*
 * This definition must be set in order for the application to handle CSA. It is used only in the
 * application.
 */
// #define APP_SUPPORTS_CLIENT_SIDE_AUTHENTICATION

/*
 * This definition tells the protocol whether the application uses CSA or not.
 * It can be set to one of the two following values:
 * - SECURITY_AUTHENTICATION_SSA
 * - SECURITY_AUTHENTICATION_CSA
 */
//@ [REQUESTED_SECURITY_AUTHENTICATION]
#define REQUESTED_SECURITY_AUTHENTICATION SECURITY_AUTHENTICATION_SSA
//@ [REQUESTED_SECURITY_AUTHENTICATION]
//@ [SECURITY_AUTHENTICATION_ID]

/**
 * Security keys
 */
//@ [REQUESTED_SECURITY_KEYS_ID]
#define REQUESTED_SECURITY_KEYS (SECURITY_KEY_S0_BIT | SECURITY_KEY_S2_UNAUTHENTICATED_BIT | SECURITY_KEY_S2_AUTHENTICATED_BIT)
//@ [REQUESTED_SECURITY_KEYS_ID]

#endif /* _CONFIG_APP_H_ */

